version: "3.9"

services:

  portainer:
    image: portainer/portainer-ce
    #user: "${FILE_OWNER_PUID}:${FILE_OWNER_PGID}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${STACK_ROOT}/services/portainer/data:/data
    ports:
      - "${PORT_PORTAINER_MAIN}:9000"
      #- "$disabled{PORT_PORTAINER_MAIN_SECURE}:9443"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    environment:
      - "PUID=${FILE_OWNER_PUID}"
      - "PGID=${FILE_OWNER_PGID}"
      - "TZ=${LINUXSERVER_TZ}"
      - "WEBUI_PORT=${PORT_QBITTORRENT_MAIN}"
    volumes:
      - ${STACK_ROOT}/services/qbittorrent/config:/config
      - ${STACK_ROOT}/files/Downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "${PORT_QBITTORRENT_MAIN}:${PORT_QBITTORRENT_MAIN}"
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    environment:
      - "PUID=${FILE_OWNER_PUID}"
      - "PGID=${FILE_OWNER_PGID}"
    volumes:
      - ${STACK_ROOT}/services/filebrowser/config:/config
      - ${STACK_ROOT}/services/filebrowser/database:/database
      - ${STACK_ROOT}/files:/srv
    ports:
      - "${PORT_FILEBROWSER_MAIN}:80"
      