version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      - "${STACK_ROOT}/services/portainer/data:/data"
      - "${STACK_ROOT}:/stack-root"
    ports:
      - "${PORT_PORTAINER_HTTP}:9000"
      - "${PORT_PORTAINER_HTTPS}:9443"
    restart: unless-stopped